project 'Pizza Client.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pizza Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pizza Client
  pod 'Alamofire', '~> 4.7'

  target 'Pizza ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pizza ClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
